### ISSUE TITLE
Promptly: Anthropic processor always run in parallel

### ISSUE THREAD

**Issue by tomasmcm** [trypromptly/LLMStack#261]
**Describe the bug**
If I have 2 or more Anthropic processors in a Web App they always run in parallel. Even when I define messages in the second processor that use the first processor as input.

**To Reproduce**

1. Create a new Web App
2. Add an Anthropic processor with 1 user message
3. Add an Anthropic processor with 1 user message (the same as in step 2.), 1 assistant message (with the output of step 2.), and 1 user message (with a new message)
4. Run the app

**Expected behavior**
Since the second processor depends on the output of the first it should only run after the first one finishes, as it happens with the Azure processor for example

**Version**
Latest

**Environment**
Chrome Mac

**Comment by ajhai** [comment]
@tomasmcm can you share your app yaml so we can replicate this and see whats happening?

**Comment by tomasmcm** [comment]
@ajhai of course. Here you go:
```
name: step1
config:
  layout: |-
    <pa-layout sx='{"maxWidth": "1200px", "margin": "10px auto"}'>
      <pa-paper style="padding: 10px;">
        <pa-grid container="true" spacing="2" style="width: 100%">
          <pa-grid item="true" xs="12">
            <pa-input-form workflow="true"></pa-input-form>
          </pa-grid>
          <pa-grid item="true" xs="12">
            <br/>
          </pa-grid>
          <pa-grid item="true" xs="12">
            <pa-workflow-output showHeader="true"></pa-workflow-output>
          </pa-grid>
        </pa-grid>
      </pa-paper>
    </pa-layout>
  allowed_sites: []
  input_template: ''
type_slug: web
processors:
  - id: messages1
    name: Messages
    input:
      messages:
        - role: user
          message: 'My name is {{_inputs0.Field1}} '
    config:
      model: claude-3-haiku
      max_tokens: 256
      temperature: 0.5
      system_prompt: ''
      retain_history: false
    description: Claude chat messages
    input_fields: []
    provider_slug: anthropic
    processor_slug: messages
    output_template:
      markdown: '{{message}}'
  - id: messages2
    name: Messages
    input:
      messages:
        - role: user
          message: 'My name is {{_inputs0.Field1}} '
        - role: assistant
          message: '{{messages1.message}} '
        - role: user
          message: What's my name?
    config:
      model: claude-3-haiku
      max_tokens: 256
      temperature: 0.5
      system_prompt: ''
      retain_history: false
    description: Claude chat messages
    input_fields: []
    provider_slug: anthropic
    processor_slug: messages
    output_template:
      markdown: '{{message}}'
description: ''
input_fields:
  - name: Field1
    type: string
    title: Field1
    required: true
    description: Description for Field1
output_template:
  markdown: |-
    1. {{messages1.message}} 
    2. {{messages2.message}} 
version: 1
is_published: true
web_config: null
twilio_config: null
slack_config: null
discord_config: null
```
